### ISSUE TITLE
Can not run your example

### ISSUE THREAD

**Issue by yy462** [Ramprasad-Group/multi-task-learning#1]
Hello,
I failed to use this curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master get-poetry.py | python,
then I tried to install poetry by myself, but I can not run the rest code like you did mtask -h. Could you give me some ideas about this and how to fix this? I think your job here is really good! Thanks! Looking forward to your reply!

All my bests,
Yu Yang

**Comment by kuelumbus** [comment]
Please see https://python-poetry.org/docs/#installation for how to install poetry. It looks like they have recently changed the set-up process of poetry.

**Comment by yuy2018** [comment]
Hello, I already install poetry. For this paper, I saw that 36 different properties of over 13,000 polymers are supplied to deep-learning multi-task architectures. But based on the data file, it is only given 8 properties. And you also put Figure 2 Polymer property heatmap of the Pearson correlation coefficients and Figure 3 Five-fold cross-validation root mean squared errors of four machine learning models for 36 polymer properties in the paper. Do you mind explaining this to me? And now I am trying to run your code related to this paper, Do you mind providing me with other code besides the model code here, like figure 2 and figure 3? I am a little confused about this. My email is yuy2018@my.fit.edu. I will be very appreciative if you could provide those. Thanks very much!

**Comment by kuelumbus** [comment]
The data set, fingerprinting process, and trained ML models cannot be shared publicly. This repository only contains the mutlitask ML code. Hope that this is helpful.

**Comment by yuy2018** [comment]
Oh, I see. Got you. Thanks for your reply! Have a good one!
