### ISSUE TITLE
Test Part

### ISSUE THREAD

**Issue by yuy2018** [Ramprasad-Group/multi-task-learning#2]
Hello, I already successfully do poetry install and poetry shell in ubuntu, then when I do mtask -h in test, I got this error. could you please just take a look and see if you have any idea for this? I would very much appreciate it if you could help me with this. By the way, because the dataset provided only has 8 features, will that still can run successfully with this code of model? I just want to run this example and see what happens.
![image](https://user-images.githubusercontent.com/95180268/192416913-9a19df6b-9926-4b6f-86b3-525cbeef0eae.png)

**Comment by kuelumbus** [comment]
This seems to be a problem with tensorflow and your system. Make sure tensorflow works on your system.
